name: IOSteinPolls
version: '${project.version}'
main: de.thelooter.iosteinpolls.IOSteinPolls
api-version: 1.18
authors: [ thelooter ]
depend: [ProtocolLib]

commands:
  poll:
    description: "Create polls"
    usage: /poll <option>
    aliases: [polls]
